AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  insultbot

  Flings a random Shakespeare-inspired insult

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    Name: insultbot
    EndpointConfiguration: REGIONAL
  Function:
    Runtime: nodejs22.x
    Timeout: 3
    Tags:
      Application: bots
    Environment:
      Variables:
        companyId: '<companyId>'

Resources:
  InsultBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: insultbot
      CodeUri: ./
      Handler: app.handler
      Description: Flings a random Shakespeare-inspired insult
      Events:
        InsultBot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
  InsultBotFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - InsultBotFunction
    Properties:
      LogGroupName: !Sub /aws/lambda/${InsultBotFunction}
      RetentionInDays: 30

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # ServerlessRestApiProdStage is an implicit API stage created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InsultBotApiEndpoint:
    Description: 'InsultBot REST API Gateway endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}/'
  InsultBotFunction:
    Description: 'InsultBot Lambda Function ARN'
    Value: !GetAtt InsultBotFunction.Arn
  InsultBotFunctionIamRole:
    Description: 'Implicit IAM Role created for InsultBot function'
    Value: !GetAtt InsultBotFunctionRole.Arn
